### ISSUE TITLE
on_commit values stuck at the last one in a loop

### ISSUE THREAD

**Issue by jackxpeng** [carljm/django-transaction-hooks#17]
I'm using connect.on_commit(lambda: send_mail(.....)) inside a loop to notify a bunch of users. I found out that all emails were sent to the last user in the loop with identical content - for the last user too. I traced the code in pycharm and found that there were indeed separate lambdas with different memory addresses but somehow they did identical things. I ended up writing a function to loop through all recipients and using that function inside of on_commit instead of having on_commit inside the loop.

While this particular problem is solved, it makes me hesitant about using on_commit because I may accidentally have a loop around some function that has on_commit in it and I don't know if it's going to work correctly or get stuck on the last iteration's values. Also can someone explain why this happens in the first place? Is this the intended behavior? Are there any guidelines on loops? Thanks.

**Comment by carljm** [comment]
This isn't related to django-transaction-hooks, it's simply the way Python closures (that is, a function or lambda defined within another function) work. The closure binds to a name within the outer scope, not the value of that name at the time the closure is defined. So if the value of that name changes in the outer scope after the definition of the closure, it will change within the closure as well. Here's the simplest demonstration:

```
>>> def factory():
...     i = 1
...     f = lambda: i
...     i = 2
...     return f
... 
>>> func = factory()
>>> func()
2
```

Or here's a demonstration involving a loop, more similar to your case:

```
>>> funcs = []
>>> for i in range(5):
...     funcs.append(lambda: i)
... 
>>> [f() for f in funcs]
[4, 4, 4, 4, 4]
```

So this is definitely something to be aware of when using closures in Python, but it's not related to django-transaction-hooks.

**Comment by jackxpeng** [comment]
Thanks for the prompt and clear explanation. I get it now.
