### ISSUE TITLE
Where to `connection.on_commit()` for every model save?

### ISSUE THREAD

**Issue by sewpafly** [carljm/django-transaction-hooks#18]
I read the docs, but I'm still unclear as to where to put the `on_commit()` call if I wanted it to run for every save of a model...

I'm guessing that you would add a `model.post_save` receiver to `models.py` and inside the receiver add the `on_commit`?

**Comment by carljm** [comment]
You guessed right. Transaction-hooks doesn't know or care about models or model signals, it's just a generic way to "run some code after this transaction commits." So if you want to run some code after every save of a model, but only after the transaction commits, you could put a call to `on_commit` in an overridden `save()` method or a `post_save` signal handler.

**Comment by pikrzysztof** [comment]
@carljm aren't  `post_save()` and `post_delete()` signals executed for every model?
What if I want to have those signals executed *per transaction*?
