### ISSUE TITLE
Getting celery task ID

### ISSUE THREAD

**Issue by Keda87** [carljm/django-transaction-hooks#23]
Hi, I'm wrapping my function to `on_commit` function from this project.
I had an issue to get celery task ID from this transaction hook.
```python
auto = connection.on_commit(
    lambda: auto_received.apply_async(
        args=[rent_order.id],
        eta=booking.return_date + timedelta(hours=49)
    )
)
```
the `auto` variable is None, and I want to get the celery task id.

Thank in advance

**Comment by carljm** [comment]
As of Django 1.9, the `on_commit` function has been added to core Django, so this third-party package will not receive any changes other than possibly backports of critical fixes made to `on_commit` in core Django (for as long as Django 1.8 is supported). So if you want to propose a new feature for `on_commit`, it needs to be proposed on the core Django mailing list / issue tracker.

It's not possible to do what you want to do here; your `on_commit` callback isn't called until later, so it's simply not possible to return the Celery task id when you call `on_commit`, as it doesn't even exist yet. You will need to update your `on_commit` callback itself to store the Celery task ID in some other storage where you can retrieve it later.
