### ISSUE TITLE
Which version is compatible with django 1.6?

### ISSUE THREAD

**Issue by fmartins** [carljm/django-transaction-hooks#24]
Hi! 

Anyone knows which version of `django-transaction-hooks` is compatible with django 1.6?

Thank you!

**Comment by carljm** [comment]
See the latest version at https://pypi.python.org/pypi/django-transaction-hooks "django-transaction-hooks supports Django 1.6.1 and later on Python 2.6, 2.7, 3.2, and 3.3."

**Comment by fmartins** [comment]
@carljm - Thank you!
