### ISSUE TITLE
Maximum recursion depth error when save object in on_commit hooks on Mysql

### ISSUE THREAD

**Issue by marekmalek** [carljm/django-transaction-hooks#8]
I use MySQL database and I have ATOMIC_REQUESTS enabled in database settings. What I wanted to try is to modify some DB object in on_commit hook but this caused infinite loop and maximum recursion depth error was raised. Here is a simple code of my view to reproduce it:

```
def hooktest(request):

    def oncommit():
        print 'ON COMMIT'
        o = DbObject.objects.get(id=1)
        o.name = "test3"
        o.save()

    print "BEFORE"
    connection.on_commit(oncommit)
    print "AFTER"

    print DbObject.objects.all()
    return HttpResponse('OK')
```
- django version is 1.6.5, mysql version is 5.5.37

**Comment by jobelenus** [comment]
I'm still seeing this problem with the latest release 0.1.3. I don't see any other tagged releases in the repo?

**Comment by carljm** [comment]
@jobelenus 0.2 was released on PyPI last November: https://pypi.python.org/pypi/django-transaction-hooks

I just forgot to do a `git push --tags`. The tag is there now.

**Comment by jobelenus** [comment]
Ah wonderful!
